### ISSUE TITLE
Crash. Dependencies required? 

### ISSUE THREAD

**Issue by VinceKezel** [DakotaPride/Boleatte#4]
Minecraft crashes before GUI loads, and has error messages referring to boleatte. If I install mod Datapack Portals by Kryptonaught, then it loads without crash. Error was something about boleatte referring to a method in datapack portals, which was not installed at first. I can go fetch an actual log if you'd like.

Boleatte 0.3.1
Minecraft 1.19.2
Fabric 0.14.14
MultiMC 0.7.0-3714
Java 17.0.4.1

and to prevent the crash in my case:
Datapack Portals 1.2.2-1.19

**Comment by DakotaPride** [comment]
The actual log would be helpful in this case, but you don't have to provide it as of right now as I think I may know how to fix this.

**Comment by DakotaPride** [comment]
@VinceKezel once you get the chance, could you please provide the log? Thank you in advance

**Comment by VinceKezel** [comment]
log with datapack portals disabled: [https://pastebin.com/1FpsqFmY](https://pastebin.com/1FpsqFmY) ... crashed on startup

log with the only thing changed is enabled datapack portals: [https://pastebin.com/b0sjiNVb](https://pastebin.com/b0sjiNVb) ... gets into game.

**Comment by DakotaPride** [comment]
> log with the only thing changed is enabled datapack portals: https://pastebin.com/b0sjiNVb ... gets into game.

The link provided goes to an expired pastebin, I think you may have forgotten to checkmark the 'never expire' (or whatever button it is) on this one. Thank you for trying to provide the log(s) though, I'll let you know if I can do anything shortly!

**Comment by DakotaPride** [comment]
@VinceKezel Ah, now I see. Boleatte uses Custom Portal API, which allows for the mod to create custom portals to the dimension. This is most likely an issue of Custom Portal API or Boleatte requiring an external mod in order to create compatibility between the two. Does enabling the 'datapack portals' have any other issues in general? If not, then I suggest just enabling it and playing normally, as you would. Thank you, let me know if any issues persist or come up!
